[project]
name = "varphi-devkit"
version = "2.0.0"
description = "Development kit for the Varphi language"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "antlr4-python3-runtime>=4.13.2",
]
authors = [
    { name = "Hassan El-Sheikha", email = "hassan.elsheikha@utoronto.ca" }
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# 1. Tell Hatchling to include the parser directory 
#    even if it is listed in .gitignore
[tool.hatch.build.targets.wheel.force-include]
"src/varphi_devkit/parser" = "varphi_devkit/parser"

[tool.hatch.build.targets.sdist.force-include]
"src/varphi_devkit/parser" = "varphi_devkit/parser"

# 2. Pytest configuration
[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
